name: httpserver
description: Sample HTTP clients and servers
homepage: https://dart.dev/tutorials/server/httpserver

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1

